name: CI

on:
  push:
    branches: [ "main", "feature/*", "github-workflow", "small-fixes" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test-macos:
    name: Build & Test macOS App
    runs-on: macos-15
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcode-select -p && xcodebuild -version

      - name: Build macOS App
        run: |
          xcodebuild -project BatteryProtect.xcodeproj \
                     -scheme BatteryProtect \
                     -configuration Debug \
                     -destination 'platform=macOS' \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                     build

      - name: Run macOS Unit Tests
        run: |
          xcodebuild -project BatteryProtect.xcodeproj \
                     -scheme BatteryProtect \
                     -configuration Debug \
                     -destination 'platform=macOS' \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                     test

  build-and-test-ios:
    name: Build & Test iOS App
    runs-on: macos-15
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcode-select -p && xcodebuild -version

      - name: Build iOS App
        run: |
          xcodebuild -project BatteryProtect.xcodeproj \
                     -scheme BatteryProtectiOS \
                     -configuration Debug \
                     -destination 'generic/platform=iOS' \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                     build

      - name: Run iOS Unit Tests
        run: |
          xcodebuild -project BatteryProtect.xcodeproj \
                     -scheme BatteryProtectiOS \
                     -configuration Debug \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
                     test
